---
- hosts: all
  tasks:
    - name: Create Deployment Directory
      file:
        path: /home/ubuntu/dfe
        state: directory

    - name: Copy staging.env File
      copy:
        src: ./staging.env
        dest: /home/ubuntu/dfe/staging.env
      loop: "{{ query('fileglob', './staging.env') }}"

    - name: Copy production.env File
      copy:
        src: ./production.env
        dest: /home/ubuntu/dfe/production.env
      loop: "{{ query('fileglob', './production.env') }}"

    - name: Copy Docker Swarm Stack File
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/dfe/docker-compose.yml

    - name: Copy Caddy File
      copy:
        src: ./Caddyfile
        dest: /home/ubuntu/dfe/Caddyfile
      register: Domain

    - name: Login Into Docker hub Registry
      community.docker.docker_login:
        username: "{{ lookup('env','DOCKER_USERNAME') }}"
        password: "{{ lookup('env','DOCKER_PASSWORD') }}"
        reauthorize: yes

    - name: Stack History limit
      shell: docker swarm update --task-history-limit 2

    - name: Deploy Production Stack
      shell: |
        cd /home/ubuntu/dfe
        docker stack deploy -c <(docker-compose config) dfe --with-registry-auth
        sleep 60
      args:
        executable: /bin/bash

    - name: Update Webserver in case of DNS change
      shell: docker service update --force dfe_webserver
      when: Domain.changed

    - name: Prune Useless Docker Images
      shell: |
        docker container prune -f
        docker image prune -a -f

    - name: List Images & Containers for SHA256 Comparsion if needed
      shell: |
        docker image ls
        docker stack ps dfe