name: Lint, Test and Build

env:
  CI: true
  MONGO_INITDB_DATABASE: 'db'

on: pull_request
jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '16'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '4.0'
          mongodb-port: 27017

      - run: yarn
      - run: yarn bootstrap
      - run: yarn lint:check

      - run: yarn test

      - run: yarn build
